name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - name: Install iverilog
      run: sudo apt-get install -y build-essential libboost-dev iverilog
    - name: Install verilator
      run: |
        sudo apt-get install -y git perl python3 make autoconf g++ flex bison ccache libgoogle-perftools-dev numactl perl-doc libfl-dev libfl2 zlibc zlib1g zlib1g-dev
        git clone https://github.com/verilator/verilator
        cd verilator
        git checkout stable
        autoconf
        ./configure
        make -j `nproc`
        sudo make install
    - name: Test
      run: sbt test
    - name: Generate verilog
      run: sbt "runMain wavebpf.WbpfVerilogSyncReset"
