name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - name: Install verilator
      run: sudo apt update && sudo apt install -y verilator
    - name: Test
      run: sbt test
    - name: Generate verilog
      run: sbt "runMain wavebpf.WbpfVerilogSyncReset"
